### ISSUE TITLE
controller generator fails

### ISSUE THREAD

**Issue by mahpour** [olohmann/generator-ng-ts#1]
I get an error when I try to generate a controller:

yo ng-ts:controller accountController

Unhandled rejection ReferenceError: relativeModulePath is not defined
    at /usr/local/lib/node_modules/generator-ng-ts/ng-ts-environment.js:54:13
    at tryCatcher (/usr/local/lib/node_modules/generator-ng-ts/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/generator-ng-ts/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/generator-ng-ts/node_modules/bluebird/js/main/promise.js:565:18)
    at Async._drainQueue (/usr/local/lib/node_modules/generator-ng-ts/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/generator-ng-ts/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/usr/local/lib/node_modules/generator-ng-ts/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:358:17)

**Comment by olohmann** [comment]
1d2d8851d11e511ae4188f377d785c1593349719 fixed issue.
